name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build script found, skipping build."
          else
            echo "No package.json found, skipping build."
          fi

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            dist/ # Adjust this path to your build output folder
            public/ # Alternative path for plain HTML/CSS/JS files

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
