name: Playwright Tests and Deployment

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5: Run Playwright Tests
      - name: Run Playwright Tests
        run: npx playwright test --reporter=html

      # Step 6: Upload Playwright Report
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy-report:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Download Playwright Report
      - name: Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report

      # Step 3: Copy Playwright Report to Public Directory
      - name: Copy Playwright Report
        run: |
          rm -rf public
          mkdir -p public
          cp -R playwright-report/* public/

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./public

  pages-build-deployment:
    needs: deploy-report
    runs-on: ubuntu-latest

    steps:
      # Step 1: Trigger Pages Deployment
      - name: Trigger Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./public
