name: Playwright Tests

on:
  push:
    branches:
      - main  # Only run the workflow on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright Tests
        run: npx playwright test --reporter=html

      # Upload Playwright report as an artifact
      - uses: actions/upload-artifact@v4
        name: Save Playwright Report
        with:
          name: playwright-report
          path: playwright-report/

  deploy-report:
    needs: test  # Ensures it runs after the test job completes
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Download Playwright report artifact
      - name: Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report

      # Copy the report to the deployment directory
      - name: Prepare Report for Deployment
        run: |
          mkdir -p public
          cp -r playwright-report/* public/

      # Deploy the report to the branch where the workflow ran
      - name: Deploy Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: ${{ github.ref_name }}  # Deploy to the same branch
